-- MySQL Script generated by MySQL Workbench
-- Sat 29 Jul 2017 01:51:32 PM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema teste_duosystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teste_duosystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teste_duosystem` DEFAULT CHARACTER SET utf8 ;
USE `teste_duosystem` ;

-- -----------------------------------------------------
-- Table `teste_duosystem`.`task_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste_duosystem`.`task_status` (
  `idtaskstatus` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `dt_created` DATETIME NOT NULL,
  `deleted` TINYINT(1) NULL,
  `dt_deleted` DATETIME NULL,
  PRIMARY KEY (`idtaskstatus`))
  ENGINE = InnoDB
  COMMENT = 'Tabela que ira guardar os dados dos status das tarefas.';

INSERT INTO `teste_duosystem`.`task_status` (name, description, dt_created) VALUES
  ('Pendente', 'tarefa não iniciada', NOW()),
  ('Em Desenvolvimento', 'tarefa em andamento', NOW()),
  ('Em Teste', 'tarefa em andamento', NOW()),
  ('Concluído', 'tarefa finalizada', NOW());

-- -----------------------------------------------------
-- Table `teste_duosystem`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste_duosystem`.`task` (
  `idtask` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT(600) NOT NULL,
  `situation` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1 - ativo\n0 - inativo',
  `dt_begin` DATE NOT NULL,
  `dt_end` DATE NULL,
  `dt_created` DATETIME NOT NULL,
  `deleted` TINYINT(1) NULL,
  `dt_deleted` DATETIME NULL,
  `task_status_idtask` INT NOT NULL,
  PRIMARY KEY (`idtask`, `task_status_idtask`),
  INDEX `fk_task_task_status_idx` (`task_status_idtask` ASC),
  CONSTRAINT `fk_task_task_status`
  FOREIGN KEY (`task_status_idtask`)
  REFERENCES `teste_duosystem`.`task_status` (`idtaskstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  COMMENT = 'Tabela em que irá conter as tarefas a serem cadastradas e gerenciadas pelo sistema.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
